apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: nitinalexvaidyan/converter-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
